<table align='center' id='borBot' width='700px'>
<tr height='30px' >
	<td id='padL15' align='left'>
		<a href='index.php' style='color:#1f7044;'>
			Home
		</a>&nbsp;
		<a href='music.php'>
			Music
		</a>
		&nbsp;
		<a href='people.php'>
			People
		</a>
		&nbsp;
		<a href='labels.php'>
			Label
		</a>
		&nbsp;
		<a href='activities.php'>
			Activities
		</a>
	</td>
	<td width='180px'>
		<form action='search.php' method='post'>
			<input class='new' type='text' name='keyword'  maxlength='50'>
	</td>
	<td width='30px' height='30px' align='center'>
<input type='submit' name='' value='' style='background-image:url(img/srch.png); background-color:#CCC; background-position:center; background-repeat:no-repeat; border:none; height:30px; width:30px; cursor:pointer;'/>
			</form>
	</td>
</tr>
</table>